/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dnebinger.vitamins.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PersistedVitamin service. Represents a row in the &quot;NEB_PersistedVitamin&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dnebinger.vitamins.model.impl.PersistedVitaminModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dnebinger.vitamins.model.impl.PersistedVitaminImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PersistedVitamin
 * @generated
 */
@ProviderType
public interface PersistedVitaminModel
	extends BaseModel<PersistedVitamin>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a persisted vitamin model instance should use the {@link PersistedVitamin} interface instead.
	 */

	/**
	 * Returns the primary key of this persisted vitamin.
	 *
	 * @return the primary key of this persisted vitamin
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this persisted vitamin.
	 *
	 * @param primaryKey the primary key of this persisted vitamin
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this persisted vitamin.
	 *
	 * @return the uuid of this persisted vitamin
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this persisted vitamin.
	 *
	 * @param uuid the uuid of this persisted vitamin
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the persisted vitamin ID of this persisted vitamin.
	 *
	 * @return the persisted vitamin ID of this persisted vitamin
	 */
	public long getPersistedVitaminId();

	/**
	 * Sets the persisted vitamin ID of this persisted vitamin.
	 *
	 * @param persistedVitaminId the persisted vitamin ID of this persisted vitamin
	 */
	public void setPersistedVitaminId(long persistedVitaminId);

	/**
	 * Returns the surrogate ID of this persisted vitamin.
	 *
	 * @return the surrogate ID of this persisted vitamin
	 */
	@AutoEscape
	public String getSurrogateId();

	/**
	 * Sets the surrogate ID of this persisted vitamin.
	 *
	 * @param surrogateId the surrogate ID of this persisted vitamin
	 */
	public void setSurrogateId(String surrogateId);

	/**
	 * Returns the group ID of this persisted vitamin.
	 *
	 * @return the group ID of this persisted vitamin
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this persisted vitamin.
	 *
	 * @param groupId the group ID of this persisted vitamin
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this persisted vitamin.
	 *
	 * @return the company ID of this persisted vitamin
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this persisted vitamin.
	 *
	 * @param companyId the company ID of this persisted vitamin
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this persisted vitamin.
	 *
	 * @return the user ID of this persisted vitamin
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this persisted vitamin.
	 *
	 * @param userId the user ID of this persisted vitamin
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this persisted vitamin.
	 *
	 * @return the user uuid of this persisted vitamin
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this persisted vitamin.
	 *
	 * @param userUuid the user uuid of this persisted vitamin
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this persisted vitamin.
	 *
	 * @return the user name of this persisted vitamin
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this persisted vitamin.
	 *
	 * @param userName the user name of this persisted vitamin
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this persisted vitamin.
	 *
	 * @return the create date of this persisted vitamin
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this persisted vitamin.
	 *
	 * @param createDate the create date of this persisted vitamin
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this persisted vitamin.
	 *
	 * @return the modified date of this persisted vitamin
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this persisted vitamin.
	 *
	 * @param modifiedDate the modified date of this persisted vitamin
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the group name of this persisted vitamin.
	 *
	 * @return the group name of this persisted vitamin
	 */
	@AutoEscape
	public String getGroupName();

	/**
	 * Sets the group name of this persisted vitamin.
	 *
	 * @param groupName the group name of this persisted vitamin
	 */
	public void setGroupName(String groupName);

	/**
	 * Returns the article ID of this persisted vitamin.
	 *
	 * @return the article ID of this persisted vitamin
	 */
	@AutoEscape
	public String getArticleId();

	/**
	 * Sets the article ID of this persisted vitamin.
	 *
	 * @param articleId the article ID of this persisted vitamin
	 */
	public void setArticleId(String articleId);

	/**
	 * Returns the description of this persisted vitamin.
	 *
	 * @return the description of this persisted vitamin
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this persisted vitamin.
	 *
	 * @param description the description of this persisted vitamin
	 */
	public void setDescription(String description);

	/**
	 * Returns the name of this persisted vitamin.
	 *
	 * @return the name of this persisted vitamin
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this persisted vitamin.
	 *
	 * @param name the name of this persisted vitamin
	 */
	public void setName(String name);

	/**
	 * Returns the type of this persisted vitamin.
	 *
	 * @return the type of this persisted vitamin
	 */
	public int getType();

	/**
	 * Sets the type of this persisted vitamin.
	 *
	 * @param type the type of this persisted vitamin
	 */
	public void setType(int type);

}